# Generated by Django 5.2.5 on 2025-09-02 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="profile",
            table="profile",
        ),
    ]
