# Generated by Django 5.2.5 on 2025-09-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_alter_task_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
