# Generated by Django 5.2.5 on 2025-09-02 19:50

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_alter_task_attachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                upload_to="attachments/",
            ),
        ),
    ]
